### PR TITLE
Version bump and chores

### LINKED ISSUE #5: could not compile `rusty_v8`
error description:  
   I copied the example from the README, and then I encountered this error when compiling and running.

my current enviroment:  
        system version: Windows 11 22000.184  
       rustc version: rustc 1.54.0  
       cargo version: cargo 1.54.0  

```toml
[package]
name = "jsdemo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sandbox = "0.1.6"
```

```rust
use js_sandbox::{Script, AnyError};

fn main() -> Result<(), AnyError> {
	let src = r#"
		function toString(person) {
			return "A person named " + person.name + " of age " + person.age;
		}"#;

	let mut script = Script::from_string(src)
		.expect("Initialization succeeds");
	Ok(())
}
```

more info
```powershell
PS F:\repos\rust\jsdemo> cargo build    
   Compiling rusty_v8 v0.22.3
   Compiling serde_v8 v0.2.0
   Compiling deno_core v0.84.0
error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `rusty_v8`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

### PR DESCRIPTION
**Pull request by Chaostheorie**
- All dependency versions (deno_core, serde, serde_json) and the rust version (2018 -> 2022) bumped. 
- Code formatted with `rustfmt`
- All deprecated uses of `JsRuntime::execute` were changed to updated name `JsRuntime::execute_script`
- There was an ops id sync problem that required a small fix to the script execution and initialization.

> This PR will most likely also fix #5 by changing the deno_core dependency to v8 from rusty_v8. This might not add any more code but has at least for me fixed the described error. 

All tests are on rust stable 1.57.0 passing.

Cheers,
Cobalt

### CODE REVIEW

**Comment by Bromeon** [comment]
Hey, thanks a lot for all these updates! 🙂 

One small request: as I'm using tabs, could you add a `rustfmt.toml` file with the [`hard_tabs`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#hard_tabs) option set to true? The other settings don't matter for now, could still be tweaked later.

**Comment by Chaostheorie** [comment]
That should've done it.

**Comment by Chaostheorie** [comment]
argh, I'll fix it later

**Comment by Bromeon** [comment]
Yeah, no rush 🙂 could you also run `cargo fmt` with the new settings?

**Comment by Chaostheorie** [comment]
Ran `cargo fmt`, fixed `rustfmt.toml` filename, removed merge duplicates

**Comment by Bromeon** [comment]
Thanks! It's OK, there are already some breaking changes from #3, I will anyway have another look. Next release is probably going to be 0.2.0, so breaking changes are possible.

**Pull request merged**
