### PR TITLE
Added ability to run async functions

### PR DESCRIPTION
**Pull request by finally0**
#10

### CODE REVIEW

**Comment by Bromeon** [comment]
Thanks, that's a nice addition! 🙂 

This implementation blocks on async functions until completion.
Could you maybe add a doc line to `Script::call()` that clarifies this behavior?

**Comment by finally0** [comment]
> Thanks, that's a nice addition! 🙂
> 
> This implementation blocks on async functions until completion. Could you maybe add a doc line to `Script::call()` that clarifies this behavior?

Added a doc line along with an example in the readme, hope that's okay? 😄

**Comment by Bromeon** [comment]
Generally yes, but ReadMe.md begins with a comment `<!-- DO NOT EDIT -- ReadMe is generated from lib.rs -->` 😉 
So you would need to apply the changes in `lib.rs` and then run this command:
```
cargo readme --no-license --template ../cfg/ReadMe.in > ../ReadMe.md
```
(needs cargo-readme; see also [CI job](https://github.com/Bromeon/js-sandbox/actions/runs/3716446303/jobs/6303855831))

But don't spend too much time on it, I'm also totally fine with just the docs.

**Comment by Bromeon** [comment]
You introduced lots of whitespace changes... Can you revert them?

I'd say we skip ReadMe + lib.rs for now and leave it at the API documentation, otherwise this PR needs an entire ping-pong tournament 😉

**Comment by finally0** [comment]
> You introduced lots of whitespace changes... Can you revert them?
> 
> I'd say we skip ReadMe + lib.rs for now and leave it at the API documentation, otherwise this PR needs an entire ping-pong tournament 😉

Reverted it back and only added the doc line!

Another thing that I spotted, deno_core re-exports futures, should we rather use that instead of adding the dependency ourselves?

**Comment by Bromeon** [comment]
> Another thing that I spotted, deno_core re-exports futures, should we rather use that instead of adding the dependency ourselves?

Oh good catch, yes if that's already availalbe, I'd use that! It should also avoid conflicts with different versions.

**Comment by Bromeon** [comment]
Thanks a lot for this feature! 🙂 
Closes #10.

**Pull request merged**
